### ISSUE TITLE
Simpler route names

### ISSUE THREAD

**Issue by redstone-dev** [NotFenixio/Voyager#2]
Ex. Instead of `/v1/forum/category/topics/<category>/<page>` make it `/v1/forums/<category>/get-topics`

**Comment by NotFenixio** [comment]
I don't know, maybe it's better to maintain ScratchDB's original routes so we only have to change the domain, what do you think?

**Comment by redstone-dev** [comment]
> I don't know, maybe it's better to maintain ScratchDB's original routes so we only have to change the domain, what do you think?

That’s a good point.

**Comment by NotFenixio** [comment]
Yeah. I'll close this for now, you can always reopen it.
